name: Manual Trigger Az ML Dev & Prd Jobs

on:
  workflow_dispatch:

jobs:
  train-experiment:
    runs-on: ubuntu-latest
    environment: development
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: set current directory
      run: cd src
    - name: run pipeline
      run: az ml job create --file ./src/dev-job.yml -w mlw-mlops-labs -g rg-mlops-labs

jobs:
  train-production:
    needs: train-experiment
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: set current directory
      run: cd src
    - name: run pipeline
      run: az ml job create --file ./src/prd-job.yml -w mlw-mlops-labs -g rg-mlops-labs --stream